document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<footer id=\'footer\' class=\'footer\'>");
document.writeln("			<address>");
document.writeln("				<strong>FLD</strong><br />");
document.writeln("				<abbr title=\'Tel\'>Tel:</abbr>");
document.writeln("				(123) 456 - 789");
document.writeln(" 			</address>");
document.writeln("			<address> ");
document.writeln("					<strong>fldqiuyu</strong>");
document.writeln("					<a href=\'http://www.cnblogs.com/fldqiuyu/\'>等等点点滴滴</a>");
document.writeln("				</address>");
document.writeln("		</footer>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");