document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<title>JS每日练习一</title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("	    <article class=\'main\'>");
document.writeln("	    	<section>");
document.writeln("	    		<h3>JavaScript练习</h3>");
document.writeln("	    	</section>");
document.writeln("	    </article>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");